version: "3.8"
services:
  api:
    container_name: bls
    image: bls
    build: .
    depends_on:
      - db
    ports:
      - "8100:8100"

  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bikelife
    ports:
      - "5432:5432"
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
      - ./migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql



